name: CI

on:
  schedule:
  - cron:  '*/20 * * * *'
  workflow_dispatch:

jobs:
  lscpu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - run: |
          echo '# Welcome' > README.md
          date --utc >> README.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
